import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [jwt, setJwt] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Summer Secret 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Hack club summer secret 2022</h1>
      <input type="password" placeholder="password" id="password" />
      <button
        onClick={() => {
          let password = document.getElementById("password").value;
          let token = "";

          fetch("/api/generateJWT?password=" + password)
            .then((res) => {
              return res.json();
            })
            .then((data) => {
              token = data.token;
              window.location.href = "/secret?jwt=" + token;
            })
            .catch((err) => {
              console.log(err);
            });
        }}
      >
        {" "}
        submit{" "}
      </button>
    </div>
  );
}
